name: "update-toc-action"
description: "Updates interface version of World of Warcraft TOC files"
inputs:
  toc-path:
    description: "Path to toc file"
    required: true
  product:
    description: "Product id to use for the default '## Version: xxx' in the TOC. If using BigWigs packager, 'Version-Classic', etc. will be updated independently."
    default: retail
runs:
  using: composite
  steps:
    - shell: bash
      run: bash "${{ github.action_path }}/script.sh" "${{ inputs.toc-path }}" "${{ inputs.product }}"
